const demos = [
  {
    name: "Dashboard",
    screenshotLight: "img/screenshots/dashboard.png",
    screenshotDark: "img/screenshots/dashboard-dark.png",
    link: "/dashboard.html",
    new: false,
  },
  {
    name: "Blank",
    screenshotLight: "img/screenshots/blank.png",
    screenshotDark: "img/screenshots/blank-dark.png",
    link: "/blank.html",
    new: false,
  },
  {
    name: "Apex Charts",
    screenshotLight: "img/screenshots/charts-apex.png",
    screenshotDark: "img/screenshots/charts-apex-dark.png",
    link: "/charts-apex.html",
    new: false,
  },
  {
    name: "Billboard Charts",
    screenshotLight: "img/screenshots/charts-billboard.png",
    screenshotDark: "img/screenshots/charts-billboard-dark.png",
    link: "/charts-billboard.html",
    new: false,
  },
  {
    name: "Data Widgets",
    screenshotLight: "img/screenshots/widgets-data.png",
    screenshotDark: "img/screenshots/widgets-data-dark.png",
    link: "/widgets-data.html",
    new: false,
  },
  {
    name: "Social Widgets",
    screenshotLight: "img/screenshots/widgets-social.png",
    screenshotDark: "img/screenshots/widgets-social-dark.png",
    link: "/widgets-social.html",
    new: false,
  },
  {
    name: "Feed",
    screenshotLight: "img/screenshots/feed-main.png",
    screenshotDark: "img/screenshots/feed-main-dark.png",
    link: "/feed-main.html",
    new: false,
  },
  {
    name: "Post",
    screenshotLight: "img/screenshots/feed-post.png",
    screenshotDark: "img/screenshots/feed-post-dark.png",
    link: "/feed-post.html",
    new: false,
  },
  {
    name: "Login",
    screenshotLight: "img/screenshots/login.png",
    screenshotDark: "img/screenshots/login-dark.png",
    link: "/login.html",
    new: false,
  },
  {
    name: "Signup",
    screenshotLight: "img/screenshots/signup.png",
    screenshotDark: "img/screenshots/signup-dark.png",
    link: "/signup.html",
    new: false,
  },
  {
    name: "Document List",
    screenshotLight: "img/screenshots/document-list.png",
    screenshotDark: "img/screenshots/document-list-dark.png",
    link: "/document-list.html",
    new: false,
  },
  {
    name: "Document Details",
    screenshotLight: "img/screenshots/document-details.png",
    screenshotDark: "img/screenshots/document-details-dark.png",
    link: "/document-details.html",
    new: false,
  },
  {
    name: "Invoice",
    screenshotLight: "img/screenshots/document-invoice.png",
    screenshotDark: "img/screenshots/document-invoice-dark.png",
    link: "/document-invoice.html",
    new: false,
  },
  {
    name: "Project List",
    screenshotLight: "img/screenshots/projects-list.png",
    screenshotDark: "img/screenshots/projects-list-dark.png",
    link: "/projects-list.html",
    new: false,
  },
  {
    name: "Project Details",
    screenshotLight: "img/screenshots/projects-details.png",
    screenshotDark: "img/screenshots/projects-details-dark.png",
    link: "/projects-details.html",
    new: false,
  },
  {
    name: "Project Task",
    screenshotLight: "img/screenshots/projects-task.png",
    screenshotDark: "img/screenshots/projects-task-dark.png",
    link: "/projects-task.html",
    new: false,
  },
  {
    name: "My Tasks",
    screenshotLight: "img/screenshots/projects-mytasks.png",
    screenshotDark: "img/screenshots/projects-mytasks-dark.png",
    link: "/projects-mytasks.html",
    new: false,
  },
  {
    name: "Events",
    screenshotLight: "img/screenshots/events-board.png",
    screenshotDark: "img/screenshots/events-board-dark.png",
    link: "/events-board.html",
    new: false,
  },
  {
    name: "Contact List",
    screenshotLight: "img/screenshots/contacts-list.png",
    screenshotDark: "img/screenshots/contacts-list-dark.png",
    link: "/contacts-list.html",
    new: false,
  },
  {
    name: "Contact Grid",
    screenshotLight: "img/screenshots/contacts-grid.png",
    screenshotDark: "img/screenshots/contacts-grid-dark.png",
    link: "/contacts-grid.html",
    new: false,
  },
  {
    name: "Contact Details",
    screenshotLight: "img/screenshots/contacts-single.png",
    screenshotDark: "img/screenshots/contacts-single-dark.png",
    link: "/contacts-single.html",
    new: false,
  },
  {
    name: "CRM Boards",
    screenshotLight: "img/screenshots/crm-boards.png",
    screenshotDark: "img/screenshots/crm-boards-dark.png",
    link: "/crm-boards.html",
    new: false,
  },
  {
    name: "CRM Kanban",
    screenshotLight: "img/screenshots/crm-kanban.png",
    screenshotDark: "img/screenshots/crm-kanban-dark.png",
    link: "/crm-kanban.html",
    new: false,
  },
  {
    name: "CRM Deal",
    screenshotLight: "img/screenshots/crm-deal.png",
    screenshotDark: "img/screenshots/crm-deal-dark.png",
    link: "/crm-deal.html",
    new: false,
  },
  {
    name: "Support Dashboard",
    screenshotLight: "img/screenshots/support-dashboard.png",
    screenshotDark: "img/screenshots/support-dashboard-dark.png",
    link: "/support-dashboard.html",
    new: false,
  },
  {
    name: "Support Tickets",
    screenshotLight: "img/screenshots/support-tickets.png",
    screenshotDark: "img/screenshots/support-tickets-dark.png",
    link: "/support-tickets.html",
    new: false,
  },
  {
    name: "Support Ticket",
    screenshotLight: "img/screenshots/support-ticket.png",
    screenshotDark: "img/screenshots/support-ticket-dark.png",
    link: "/support-ticket.html",
    new: false,
  },
  {
    name: "Datatable Basic",
    screenshotLight: "img/screenshots/datatable-basic.png",
    screenshotDark: "img/screenshots/datatable-basic-dark.png",
    link: "/datatable-basic.html",
    new: false,
  },
  {
    name: "Datatable Variations",
    screenshotLight: "img/screenshots/datatable-variations.png",
    screenshotDark: "img/screenshots/datatable-variations-dark.png",
    link: "/datatable-variations.html",
    new: false,
  },
  {
    name: "Datatable Advanced",
    screenshotLight: "img/screenshots/datatable-advanced.png",
    screenshotDark: "img/screenshots/datatable-advanced-dark.png",
    link: "/datatable-advanced.html",
    new: false,
  },
  {
    name: "Chat",
    screenshotLight: "img/screenshots/chat.png",
    screenshotDark: "img/screenshots/chat-dark.png",
    link: "/chat.html",
    new: false,
  },
  {
    name: "Inbox",
    screenshotLight: "img/screenshots/inbox.png",
    screenshotDark: "img/screenshots/inbox-dark.png",
    link: "/inbox.html",
    new: false,
  },
  {
    name: "Forum Home",
    screenshotLight: "img/screenshots/forum-home.png",
    screenshotDark: "img/screenshots/forum-home-dark.png",
    link: "/forum-home.html",
    new: false,
  },
  {
    name: "Forum Channel",
    screenshotLight: "img/screenshots/forum-channel.png",
    screenshotDark: "img/screenshots/forum-channel-dark.png",
    link: "/forum-channel.html",
    new: false,
  },
  {
    name: "Forum Topic",
    screenshotLight: "img/screenshots/forum-topic.png",
    screenshotDark: "img/screenshots/forum-topic-dark.png",
    link: "/forum-topic.html",
    new: false,
  },
];

export function initRenderDemos() {
  return {
    screenshots: demos,
  };
}
