const demos = [
  {
    name: "Dashboard",
    screenshotLight: "img/screenshots/dashboard.png",
    screenshotDark: "img/screenshots/dashboard-dark.png",
    link: "/dashboard",
    new: false,
  },
  {
    name: "Blank",
    screenshotLight: "img/screenshots/blank.png",
    screenshotDark: "img/screenshots/blank-dark.png",
    link: "/blank",
    new: false,
  },
  {
    name: "Apex Charts",
    screenshotLight: "img/screenshots/charts-apex.png",
    screenshotDark: "img/screenshots/charts-apex-dark.png",
    link: "/charts-apex",
    new: false,
  },
  {
    name: "Data Widgets",
    screenshotLight: "img/screenshots/widgets-data.png",
    screenshotDark: "img/screenshots/widgets-data-dark.png",
    link: "/widgets-data",
    new: false,
  },
  {
    name: "Social Widgets",
    screenshotLight: "img/screenshots/widgets-social.png",
    screenshotDark: "img/screenshots/widgets-social-dark.png",
    link: "/widgets-social",
    new: false,
  },
  {
    name: "Feed",
    screenshotLight: "img/screenshots/feed-main.png",
    screenshotDark: "img/screenshots/feed-main-dark.png",
    link: "/feed-main",
    new: false,
  },
  {
    name: "Post",
    screenshotLight: "img/screenshots/feed-post.png",
    screenshotDark: "img/screenshots/feed-post-dark.png",
    link: "/feed-post",
    new: false,
  },
  {
    name: "Login",
    screenshotLight: "img/screenshots/login.png",
    screenshotDark: "img/screenshots/login-dark.png",
    link: "/login",
    new: false,
  },
  {
    name: "Signup",
    screenshotLight: "img/screenshots/signup.png",
    screenshotDark: "img/screenshots/signup-dark.png",
    link: "/signup",
    new: false,
  },
  {
    name: "Document List",
    screenshotLight: "img/screenshots/document-list.png",
    screenshotDark: "img/screenshots/document-list-dark.png",
    link: "/document-list",
    new: false,
  },
  {
    name: "Document Details",
    screenshotLight: "img/screenshots/document-details.png",
    screenshotDark: "img/screenshots/document-details-dark.png",
    link: "/document-details",
    new: false,
  },
  {
    name: "Invoice",
    screenshotLight: "img/screenshots/document-invoice.png",
    screenshotDark: "img/screenshots/document-invoice-dark.png",
    link: "/document-invoice",
    new: false,
  },
  {
    name: "Project List",
    screenshotLight: "img/screenshots/projects-list.png",
    screenshotDark: "img/screenshots/projects-list-dark.png",
    link: "/projects-list",
    new: false,
  },
  {
    name: "Project Details",
    screenshotLight: "img/screenshots/projects-details.png",
    screenshotDark: "img/screenshots/projects-details-dark.png",
    link: "/projects-details",
    new: false,
  },
  {
    name: "Project Task",
    screenshotLight: "img/screenshots/projects-task.png",
    screenshotDark: "img/screenshots/projects-task-dark.png",
    link: "/projects-task",
    new: false,
  },
  {
    name: "My Tasks",
    screenshotLight: "img/screenshots/projects-mytasks.png",
    screenshotDark: "img/screenshots/projects-mytasks-dark.png",
    link: "/projects-mytasks",
    new: false,
  },
  {
    name: "Events",
    screenshotLight: "img/screenshots/events-board.png",
    screenshotDark: "img/screenshots/events-board-dark.png",
    link: "/events-board",
    new: false,
  },
  {
    name: "Contact List",
    screenshotLight: "img/screenshots/contacts-list.png",
    screenshotDark: "img/screenshots/contacts-list-dark.png",
    link: "/contacts-list",
    new: false,
  },
  {
    name: "Contact Grid",
    screenshotLight: "img/screenshots/contacts-grid.png",
    screenshotDark: "img/screenshots/contacts-grid-dark.png",
    link: "/contacts-grid",
    new: false,
  },
  {
    name: "Contact Details",
    screenshotLight: "img/screenshots/contacts-single.png",
    screenshotDark: "img/screenshots/contacts-single-dark.png",
    link: "/contacts-single",
    new: false,
  },
  {
    name: "CRM Boards",
    screenshotLight: "img/screenshots/crm-boards.png",
    screenshotDark: "img/screenshots/crm-boards-dark.png",
    link: "/crm-boards",
    new: false,
  },
  {
    name: "CRM Kanban",
    screenshotLight: "img/screenshots/crm-kanban.png",
    screenshotDark: "img/screenshots/crm-kanban-dark.png",
    link: "/crm-kanban",
    new: false,
  },
  {
    name: "CRM Deal",
    screenshotLight: "img/screenshots/crm-deal.png",
    screenshotDark: "img/screenshots/crm-deal-dark.png",
    link: "/crm-deal",
    new: false,
  },
  {
    name: "Support Dashboard",
    screenshotLight: "img/screenshots/support-dashboard.png",
    screenshotDark: "img/screenshots/support-dashboard-dark.png",
    link: "/support-dashboard",
    new: false,
  },
  {
    name: "Support Tickets",
    screenshotLight: "img/screenshots/support-tickets.png",
    screenshotDark: "img/screenshots/support-tickets-dark.png",
    link: "/support-tickets",
    new: false,
  },
  {
    name: "Support Ticket",
    screenshotLight: "img/screenshots/support-ticket.png",
    screenshotDark: "img/screenshots/support-ticket-dark.png",
    link: "/support-ticket",
    new: false,
  },
  {
    name: "Datatable",
    screenshotLight: "img/screenshots/datatable-basic.png",
    screenshotDark: "img/screenshots/datatable-basic-dark.png",
    link: "/datatable",
    new: false,
  },
  {
    name: "Chat",
    screenshotLight: "img/screenshots/chat.png",
    screenshotDark: "img/screenshots/chat-dark.png",
    link: "/chat",
    new: false,
  },
  {
    name: "Inbox",
    screenshotLight: "img/screenshots/inbox.png",
    screenshotDark: "img/screenshots/inbox-dark.png",
    link: "/inbox",
    new: false,
  },
  {
    name: "Forum Home",
    screenshotLight: "img/screenshots/forum-home.png",
    screenshotDark: "img/screenshots/forum-home-dark.png",
    link: "/forum-home",
    new: false,
  },
  {
    name: "Forum Channel",
    screenshotLight: "img/screenshots/forum-channel.png",
    screenshotDark: "img/screenshots/forum-channel-dark.png",
    link: "/forum-channel",
    new: false,
  },
  {
    name: "Forum Topic",
    screenshotLight: "img/screenshots/forum-topic.png",
    screenshotDark: "img/screenshots/forum-topic-dark.png",
    link: "/forum-topic",
    new: false,
  },
];

export function initRenderDemos() {
  return {
    screenshots: demos,
  };
}
