import { initBlank } from "./dashboard/blank";
import { initDashboard } from "./dashboard/dashboard";
import { initApexCharts } from "./charts/charts-apex";
import { initBillboardCharts } from "./charts/charts-billboard";
import { initWidgetsData } from "./widgets/widgets-data";
import { initDocumentList } from "./document/document-list";
import { initDocumentDetails } from "./document/document-details";
import { initProjectList } from "./project/project-list";
import { initProjectDetails } from "./project/project-details";
import { initProjectMyTasks } from "./project/project-mytasks";
import { initProjectTask } from "./project/project-task";
import { initEvents } from "./event/events";
import { initContactList } from "./contact/contact-list";
import { initContactGrid } from "./contact/contact-grid";
import { initContactDetails } from "./contact/contact-details";
import { initCrmDeal } from "./crm/crm-deal";
import { initCrmKanban } from "./crm/crm-kanban";
import { initSupportDashboard } from "./support/support-dashboard";
import { initSupportTicket } from "./support/support-ticket";
import { initSupportTickets } from "./support/support-tickets";
import { initDatatableBasic } from "./datatable/datatable-basic";
import { initDatatableVariations } from "./datatable/datatable-variations";
import { initDatatableAdvanced } from "./datatable/datatable-advanced";
import { initChat } from "./chat/chat";
import { initInbox } from "./inbox/inbox";
import { initForumHome } from "./forum/forum-home";
import { initForumChannel } from "./forum/forum-channel";
import { initForumTopic } from "./forum/forum-topic";

window.initBlank = initBlank;
window.initDashboard = initDashboard;
window.initApexCharts = initApexCharts;
window.initBillboardCharts = initBillboardCharts;
window.initWidgetsData = initWidgetsData;
window.initDocumentList = initDocumentList;
window.initDocumentDetails = initDocumentDetails;
window.initProjectList = initProjectList;
window.initProjectDetails = initProjectDetails;
window.initProjectMyTasks = initProjectMyTasks;
window.initProjectTask = initProjectTask;
window.initEvents = initEvents;
window.initContactList = initContactList;
window.initContactGrid = initContactGrid;
window.initContactDetails = initContactDetails;
window.initCrmDeal = initCrmDeal;
window.initCrmKanban = initCrmKanban;
window.initSupportDashboard = initSupportDashboard;
window.initSupportTicket = initSupportTicket;
window.initSupportTickets = initSupportTickets;
window.initDatatableBasic = initDatatableBasic;
window.initDatatableVariations = initDatatableVariations;
window.initDatatableAdvanced = initDatatableAdvanced;
window.initChat = initChat;
window.initInbox = initInbox;
window.initForumHome = initForumHome;
window.initForumChannel = initForumChannel;
window.initForumTopic = initForumTopic;
