import { initPageLoader } from './components/pageloader';
import { initNavbar } from './components/navbar';
import { initSidebar } from './components/sidebar';
import { initSidebarLeft } from './components/sidebar-left';
import { initSidebarRight } from './components/sidebar-right';
import { initVideoPlayers } from './components/player';
import { initMapBox } from './components/map';

import { initBlank } from './pages/blank';
import { initDashboard } from './pages/dashboard';
import { initApexCharts } from './pages/charts-apex';
import { initBillboardCharts } from './pages/charts-billboard';
import { initWidgetsData } from './pages/widgets-data';
import { initDocumentList } from './pages/document-list';
import { initDocumentDetails } from './pages/document-details';
import { initProjectList } from './pages/project-list';
import { initProjectDetails } from './pages/project-details';
import { initProjectMyTasks } from './pages/project-mytasks';
import { initProjectTask } from './pages/project-task';
import { initEvents } from './pages/events';
import { initContactList } from './pages/contact-list';
import { initContactGrid } from './pages/contact-grid';
import { initContactDetails } from './pages/contact-details';
import { initCrmDeal } from './pages/crm-deal';
import { initCrmKanban } from './pages/crm-kanban';
import { initSupportDashboard } from './pages/support-dashboard';
import { initSupportTicket } from './pages/support-ticket';
import { initSupportTickets } from './pages/support-tickets';
import { initDatatableBasic } from './pages/datatable-basic';
import { initDatatableVariations } from './pages/datatable-variations';
import { initDatatableAdvanced } from './pages/datatable-advanced';
import { initChat } from './pages/chat';
import { initInbox } from './pages/inbox';
import { initForumHome } from './pages/forum-home';
import { initForumChannel } from './pages/forum-channel';
import { initForumTopic } from './pages/forum-topic';

import { switchDemoImages, insertBgImages, initRipple } from './utils/utils';


export * from './components/pageloader';
export * from './components/navbar';
export * from './components/sidebar';
export * from './components/sidebar-left';
export * from './components/sidebar-right';
export * from './components/player';
export * from './components/map';

export * from './pages/blank';
export * from './pages/dashboard';
export * from './pages/charts-apex';
export * from './pages/charts-billboard';
export * from './pages/widgets-data';
export * from './pages/document-list';
export * from './pages/document-details';
export * from './pages/project-list';
export * from './pages/project-details';
export * from './pages/project-mytasks';
export * from './pages/project-task';
export * from './pages/events';
export * from './pages/contact-list';
export * from './pages/contact-grid';
export * from './pages/contact-details';
export * from './pages/crm-deal';
export * from './pages/crm-kanban';
export * from './pages/support-dashboard';
export * from './pages/support-ticket';
export * from './pages/support-tickets';
export * from './pages/datatable-basic';
export * from './pages/datatable-variations';
export * from './pages/datatable-advanced';
export * from './pages/chat';
export * from './pages/inbox';
export * from './pages/forum-home';
export * from './pages/forum-channel';
export * from './pages/forum-topic';

export * from './utils/utils';